# Configuration for jekyll
# NOTICE: GitHub forces to set `safe: true` in order to prohibit using plugins.
safe: true
source: .
destination: ./_site
plugins: ./_plugins
lsi: true
pygments: true
markdown: rdiscount
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md', 'vender']

# Configuration for url/path
# NOTICE:
# * `baseurl`: Being set as absolute path is recommended.
# * No need '/' at the end of url/path.
# * Project page:
#   url: http://USERNAME.github.com/REPOSITORY
#   baseurl: /REPOSITORY
url: http://USERNAME.github.com
baseurl: 

# Configuration for permalink
# `permalink`: none, pretty or /blog/:categories/:title.html
permalink: /blog/:year/:month/:title/

# Configuration for site
title: Sedky Stanley Said
description: Amateur chef | coffee connoisseur | explorer | tech lover!
author: Sedky Stanley Said
email: sedstan@sedkystanleysaid.com

# Configuration for blog
lang: en
paginate: 4
columns: 3
date_format: "%B %d, %Y"
truncate_len: 200

# Configuration for asides/recent_posts.html
recent_posts: 5

# Configuration for navbar.html
navbar_list:
- name: Blog
  link: /
  dropdown: &dropdown
  - name: Archives
    link: /blog/archives.html
  - name: Categories
    link: /blog/categories.html
  - name: Tags
    link: /blog/tags.html
- name: Project
  link: /project/
- name: About
  link: /about.html

# Configuration for bootstrap and color theme
# `bootstrap`:
# custom, original, amelia, cerulean, cyborg, journal,
# readable, simplex, slate, spacelab, spruce, superhero, united
bootstrap: slate
bootstrap_ver: 2.3.2
bootswatch_ver: 2.3.2

# Configuration for responsive break point when using 'custom'.
responsive_bp: 768

# Configuration for asides.html
# CAUTION: `themes` should be false to put the script.html at the bottom.
asides:
    about: true
    search: false
    themes: false
    recent_posts: true
    archive_tabs: true
    tweets: true
    github: false

# Configuration for pygments
# `pygments_style`:
# autumn, borland, bw, colorful, default, emacs, friendly, fruity,
# github, manni, monokai, murphy, native, pastie, perldoc, tango, trac, vs
pygments_style: github

# Configuration for jQuery
jquery_ver: 1.10.2

#-----------------------------------
# Configuration for 3rd party script
#-----------------------------------
disqus:
    short_name: USERNAME
    comment_count: true
    developer_mode: true

#feedburner:
#    id: YOUR_SITE_ID

#google_analytics:
#    account: UA-XXXXX-X

google_plus_one:
    size: medium

# `xfbml` will break some styles on android 2.3 native browser (Optimus L-01D).
# `locale`: ja_JP, en_US, es_LA, fr_FR, de_DE, it_IT, zh_CN, ko_KR, ...
facebook:
    xfbml: false
    locale: en_US

twitter:
    username: sedkyssaid
    count: 5
    exclude_replies: true
    show_screen_name: true
    show_follower_count: true
#    widget_id: 243046062967885824

github:
    username: sedstan
   count: 5

pocket: true

#hatena: true





# # Welcome to Jekyll!
# #
# # This config file is meant for settings that affect your whole blog, values
# # which you are expected to set up once and rarely need to edit after that.
# # For technical reasons, this file is *NOT* reloaded automatically when you use
# # 'jekyll serve'. If you change this file, please restart the server process.

# # Site settings
# title: Your awesome title
# email: your-email@domain.com
# description: > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "http://yourdomain.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# # Build settings
# markdown: kramdown
